[project]
name = "learnforge-support-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-generativeai>=0.8.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
learnforge-support-assistant = "learnforge_support_assistant:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
